# ローカルではresources/application-personal.yamlを読む
spring:
  profiles:
    include: personal

# App Engineの推奨に従いPORT環境変数で待ち受ける
server:
  port: ${PORT:8080}

# Bot設定
tts-bot:
  discord:
    bot-token: ${BOT_TOKEN}
  # Botへの指示語
  command:
    # ボイスチャンネルへ接続
    connect: "k.con"
    # ボイスチャンネルから切断
    disconnect: "k.dc"
  google:
    text-to-speech:
      # Google Text-to-Speech(TTS) APIのエンドポイントURL
      api-url: https://texttospeech.googleapis.com/v1/text:synthesize
      # TTS APIを叩くための認証トークン
      token: ${AUTH_TOKEN}
      # 言語
      language-code: "ja-JP"
      # 音声名
      name: "ja-JP-Wavenet-C"
      # 性別
      ssml-gender: male
      # オーディオエンコード
      audio-encoding: ogg_opus
